Ensure Java 1.8 is available on Darwin on CI
The build failed, and the logs say this:

  bazel: Java 1.8 is required to install this formula.
  Install AdoptOpenJDK 8 with Homebrew Cask:
    brew cask install homebrew/cask-versions/adoptopenjdk8
  Error: An unsatisfied requirement failed this build.

So let's try that then.